                <form class="form-horizontal" action="{:request()->url()}" method="post" id="editForm">
                    <div class="form-group">
                        <label for="title" class="col-sm-2">盘点日期</label>
                        <div class="col-sm-4">
                            <{tmdTag:date name="addtime"}>
                        </div>
                        <label for="title" class="col-sm-2">监督用户</label>
                        <div class="col-sm-4">
                            <select name="jiandu" class="mySelect" style="width: 100%">
                                <option value=""></option>
                                <?=\app\member\model\Member::option()?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-sm-2">盘点备注</label>
                        <div class="col-sm-10">
                            <textarea name="remark" rows="6" class="form-control"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="hidden" name="id" value="{$id}"/>
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </div>
                </form>

<script>
    $(function(){
        $('#editForm').myForm();
        <?php if ($one) { ?>
        var oneData = <?=json_encode($one, JSON_UNESCAPED_UNICODE)?>;
        $('#editForm').myFormData(oneData);
        <?php } ?>
        pageInit();
    })
</script>

