

<div class="panel">
    <div class="panel-heading">
        修改密码
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="{:request()->url()}" id="editForm">

            <div class="form-group">
                <label class="col-sm-2">原密码：</label>
                <div class="col-sm-10 col-md-8 col-lg-6">
                    <input type="password" class="form-control" name="old_password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2">新密码：</label>
                <div class="col-sm-10 col-md-8 col-lg-6">
                    <input type="password" class="form-control" name="new_password">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2">确认新密码：</label>
                <div class="col-sm-10 col-md-8 col-lg-6">
                    <input type="password" class="form-control" name="new_password2">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2"></label>
                <div class="col-sm-10 col-md-8 col-lg-6">
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            </div>

        </form>
    </div>
</div>

<script>
    $('#editForm').myForm();
</script>