
<div class="panel">
    <div class="panel-heading">
        角色
    </div>
    <div class="panel-body">
        <a href="{:url('role_edit')}" class="btn btn-primary">
            <i class="icon icon-plus"></i> 新增
        </a>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>角色名称</th>
                <th>备注</th>
                <th>排序</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($list as $i=>$row) {
                ?>
                <tr>
                    <td>{$i+1}</td>
                    <td>{$row.name}</td>
                    <td class="text-danger">{$row.remark}</td>
                    <td>{$row.sort}</td>
                    <td>
                        <a href="{:url('role_edit')}?id={$row.id}" class="btn btn-mini btn-primary">修改</a>
                        <a href="{:url('role_delete')}?id={$row.id}" class="btn btn-mini btn-primary tmdDelete">删除</a>
                    </td>
                </tr><?php
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
{$list->render()}