<div class="panel">
    <div class="panel-heading">
        客户搜索
    </div>
    
    <div class="panel-body">
        <div class="row">
            <script src="__INDEX__/distpicker.min.js"></script>
            <form class="form-horizontal" method="post" id="editForm" action="/member/customer/index/">

                    <div class="form-group">
                        <label class="col-sm-2">名称：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="company" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">电话：</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="mobile" placeholder="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2"> 地址：</label>
                        <div class="col-sm-10">
                            <div class="pure-g" data-toggle="distpicker">
                                <select class="form-control sm-3-5" name="province"
                                        data-province="<?= $editData['province'] ?: '' ?>">
                                </select>
                                <select class="form-control sm-3-5" name="city"
                                        data-city="<?= $editData['city'] ?: '' ?>">
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="hidden" class="form-control" name="id">
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </div>

                </form>
        </div>
    </div>

</div>