                <form class="form-horizontal" method="post" id="editForm" action="{:request()->url()}">
                    <?php $wxuser= \app\weixin\model\WxUser::get($list['wxid']); ?>
                    <div class="form-group">
                        <label class="col-sm-2">微信昵称：</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" value="{$wxuser.nickname}" disabled>
                        </div>
                        <label class="col-sm-2">联系姓名：</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" value="{$wxuser.realname}" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">所属公司：</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" value="{$wxuser.company}" disabled>
                        </div>
                        <label class="col-sm-2">联系电话：</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" value="{$wxuser.mobile}" disabled>
                        </div>
                    </div>
                    <hr>
                    <div class="form-group">
                        <label class="col-sm-2">标题:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="title">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">缩略图:</label>
                        <div class="col-sm-10">
                            <{tmdTag:upimg name="thumb"}>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">类别</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="yiren">
                        </div>
                        <label class="col-sm-2">地址</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="address">
                        </div>
                        <label class="col-sm-2">费用</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="feiyong">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">开始</label>
                        <div class="col-sm-2">
                            <{tmdTag:date name='stime' /}>
                           
                        </div>
                        <label class="col-sm-2">结束</label>
                        <div class="col-sm-2">
                            <{tmdTag:date name='etime' /}>
                        </div>
                        <label class="col-sm-2">添加</label>
                        <div class="col-sm-2">
                            <input type="text" class="form-control" name="addtime" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">艺人要求</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="10" name="yryq"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">活动内容</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="10" name="content"></textarea>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label class="col-sm-2">状态</label>
                        <div class="col-sm-4">
                            <select name="status" class="mySelect" style="width: 100%">
                                <option value="99"<?php if($list['status']=='99'){echo " selected";} ?>>审核通过</option>
                                <option value="88"<?php if($list['status']=='88'){echo " selected";} ?>>待审核</option>
                                <option value="0"<?php if($list['status']=='0'){echo " selected";} ?>>拒绝用户</option>
                            </select>

                        </div>
                        <label class="col-sm-2">电话显示</label>
                        <div class="col-sm-4">
                            <select name="ismobile" class="mySelect" style="width: 100%">
                                <option value="1"<?php if($list['status']=='1'){echo " selected";} ?>>显示电话</option>
                                <option value="0"<?php if($list['status']=='0'){echo " selected";} ?>>不显示电话</option>
                            </select>

                        </div>
                    </div>
     
               

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="hidden" class="form-control" name="id">
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </div>

                </form>

<script>pageInit();</script>
<script>
    $('#editForm').myForm();
    
    // <?php if ($list) { ?> //
    var list = <?=json_encode($list, JSON_UNESCAPED_UNICODE)?>;
    $('#editForm').myFormData(list);
    // <?php } ?> //

</script>