
<div class="panel">
    <div class="panel-heading">
        微信用户
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>头像</th>
                <th>昵称</th>
                <th>性别</th>
                <th>地区</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($list as $i=>$r) {
              $row= \app\weixin\model\WxUser::where('wxid',$r['wxid'])->find();
                ?>
                <tr>
                    <td>{$i+1}</td>
                    <td><img src="{$row.headimgurl}" alt="" width="35" height="35"/></td>
                    <td>{$row.nickname}</td>
                    <td><?php echo \my::selectText('gender',$row['sex']) ?></td>
                    <td>{$row.country}-{$row.province}-{$row.city}</td>
                    <td>
                        
                        
                    </td>
                </tr>
                <?php
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
{$list->render()}