
<div class="panel">
    <div class="panel-heading">
        微信用户
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>头像</th>
                <th>姓名</th>
                <th>昵称</th>
                <th>性别</th>
                <th>地区</th>
                <th>类型</th>
                <th>三围</th>
                <th>提交时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($list as $i=>$row) {
                ?>
                <tr>
                    <td>{$i+1}</td>
                    <td><img src="{$row.touxiang}" alt="" width="35" height="35"/></td>
                    <td>{$row.xingming}</td>
                    <td>{$row.nicheng}</td>
                    <td>{$row.xingbie}</td>
                    <td>{$row.sheng}/{$row.shi}</td>
                    <td>{$row.type}</td>
                    <td>身高:{$row.shengao}cm<Br>体重:{$row.tizhong}<br>三围:{$row.tizhong}</td>
                    <td>{$row.addtime}</td>
                    <?php if($row['status']=='88') {?>
                    <td><a class="btn btn-danger">待审核</a></td>
                    <?php }elseif($row['status']=='99'){?>
                    <td><a class="btn btn-success">审核通过</a></td>
                    <?php }else{?>
                    <td><a class="btn btn-default">已拒绝</a></td>
                    <?php }?>
                    <td>
                        <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-remote="{:url('yiren_edit')}?id={$row.id}">详细资料</button>
                        <a href="{:url('yiren_delete')}?id={$row.id}" class="btn btn-sm btn-primary tmdDelete">删除</a>
                    </td>
                </tr>
                <?php
            }
            ?>
            </tbody>
        </table>
    </div>
</div>
{$list->render()}